/* FIGARO'S PASSWORD MANAGER 2 (FPM2)
 * Copyright (C) 2000 John Conneely
 * Copyright (C) 2008-2017 Aleš Koval
 *
 * FPM is open source / free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * FPM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 *
 * interface.h - GTK Interface - originally generated by Glade
 */

GtkWidget* create_app_safe (void);
GtkWidget* create_dialog_edit_passitem (void);
GtkWidget* create_dialog_password (void);
GtkWidget* create_dialog_password_gen (void);
GtkWidget* create_dialog_cpw (void);
GtkWidget* create_dialog_launcher (void);
GtkWidget* create_dialog_about (void);
GtkWidget* create_dialog_preferences (void);
GtkWidget* create_context_menu (void);
GtkWidget* create_window_entropy (void);
GtkWidget* create_tray_menu (void);
GtkWidget* create_toolbar_menu (void);
